#!/usr/bin/python3

import sys

sum = 0
comment = ""

t = 1

for i in sys.argv[1:]:
    if t < len(sys.argv)-1:
        comment += i + "+"
    else:
        comment += i + "="
    sum +=  float(i)
    t += 1

print(comment,sum)
